### PR TITLE
feat: add `focusable` option

### PR DESCRIPTION
**Pull request by bent10**
Allowing users to set the attribute `tabindex="-1"` for improved accessibility.

### CODE REVIEW

**Comment by bent10** [comment]
I appreciate your concern. However, how about considering the performance benefits of adding the `focusable` option? The difference may not be significant, but it also offers improved accessibility and a smoother experience.

```bash
✓ marked-heading.bench.ts (2) 1218ms
     name                    hz     min     max    mean     p75     p99    p995    p999     rme  samples
   · focusable#hook      986.88  0.6852  5.1013  1.0133  1.0984  3.6768  3.9453  5.1013  ±4.47%      494  
   · focusable#option  1,196.57  0.6642  4.8428  0.8357  0.8175  3.9367  4.2163  4.8428  ±4.36%      599   fastest
```

**Comment by UziTech** [comment]
It may be faster but what about an option to add an aria-label and another option incase someone wants to use aria-labeledby. What if someone wants to set the color to be blue.

You can see how adding an option for everything can get out of hand. We need to draw the line somewhere. If you are concerned about speed another option is to create your own extension that has whatever options you want to add. 😁👍

**Comment by bent10** [comment]
You could even limit the additions to very common practices only 😅

Actually, I hope not to create another extension for this; [I've made quite a few](https://github.com/bent10/marked-extensions) this week.

Anyway, thanks for your response and your Marked 👍

**Comment by UziTech** [comment]
thanks, if you want you can add the extensions to the marked docs [known extensions](https://marked.js.org/using_advanced#extensions)

**Comment by bent10** [comment]
[Done](https://github.com/markedjs/marked/pull/3026) 🚀

**Pull request closed without merging**
